// Cloudinary integration for a static (backend-less) React site.
//
// IMPORTANT: This never uses CLOUDINARY_API_KEY or CLOUDINARY_API_SECRET.
// Those are admin credentials — putting them in any frontend code (even
// "hidden" in a .env) would ship them to every visitor's browser inside the
// compiled JS bundle. They are only used in scripts/generate-catalog.mjs,
// which runs on your computer, not in the browser.
//
// The product LIST itself comes from src/data/catalog.json, a static file
// generated by `npm run catalog`. This file just builds image URLs from
// that static data — no runtime calls to Cloudinary's API, so nothing can
// 404 because of a missing tag or a disabled "Resource list" setting.

// Cloud name is public info (it's already part of every image URL), so a
// hardcoded fallback is safe — this prevents the classic
// "res.cloudinary.com/undefined/..." bug if the VITE_CLOUDINARY_CLOUD_NAME
// env var isn't set on your hosting provider.
const FALLBACK_CLOUD_NAME = 'ds4i8pujs';

export const CLOUDINARY_CLOUD_NAME =
  (import.meta.env.VITE_CLOUDINARY_CLOUD_NAME as string) || FALLBACK_CLOUD_NAME;

export interface CloudinaryResource {
  public_id: string;
  format: string;
  width: number;
  height: number;
}

/**
 * Builds a delivery URL for a Cloudinary image with sensible default
 * transformations (auto format + auto quality + fill crop).
 */
export function cloudinaryImageUrl(
  publicId: string,
  opts: { width?: number; height?: number } = {}
): string {
  const { width = 800, height } = opts;
  const transform = height
    ? `f_auto,q_auto,c_fill,w_${width},h_${height}`
    : `f_auto,q_auto,c_fill,w_${width}`;
  return `https://res.cloudinary.com/${CLOUDINARY_CLOUD_NAME}/image/upload/${transform}/${publicId}`;
}

/**
 * Turns a Cloudinary public_id like "vignesh-metals/brass-diyas/box-kuthu-vilakku-04"
 * into a readable product name like "Box Kuthu Vilakku".
 */
export function humanizeFilename(publicId: string): string {
  const fileName = publicId.split('/').pop() ?? publicId;
  const withoutTrailingNumber = fileName.replace(/[-_\s]*\d+$/, '');
  const spaced = withoutTrailingNumber.replace(/[-_]+/g, ' ').trim();
  const humanized = spaced.replace(/\b\w/g, (c) => c.toUpperCase());
  return humanized || fileName;
}