import { useMemo } from 'react';
import catalogData from '../data/catalog.json';
import { cloudinaryImageUrl, humanizeFilename, type CloudinaryResource } from '../lib/cloudinary';
import { categoryList, type CategoryMeta } from '../data/categories';
import type { DisplayProduct } from '../types/product';

// catalog.json looks like: { "brass-diyas": [{ public_id, width, height, format }, ...], ... }
// It's generated by `npm run catalog` (scripts/generate-catalog.mjs) from your
// actual Cloudinary folders, so this is just a static in-memory lookup —
// no network requests, nothing to 404.
const catalog = catalogData as Record<string, CloudinaryResource[]>;

function toDisplayProducts(resources: CloudinaryResource[], category: CategoryMeta): DisplayProduct[] {
  return resources.map((r) => {
    const name = humanizeFilename(r.public_id);
    return {
      id: r.public_id,
      name: `${name} – ${category.name}`,
      shortName: name,
      image: cloudinaryImageUrl(r.public_id, { width: 800 }),
      alt: `${name} handcrafted ${category.material} pooja item from the ${category.name} collection`,
      material: category.material,
      category: category.name,
    };
  });
}

interface CategoryProductsState {
  products: DisplayProduct[];
  loading: boolean;
  error: string | null;
}

/** Reads every product image for a single category out of the static catalog. */
export function useCategoryProducts(category: CategoryMeta | undefined): CategoryProductsState {
  return useMemo(() => {
    if (!category) return { products: [], loading: false, error: null };

    const resources = catalog[category.slug];

    if (resources === undefined) {
      // The category folder doesn't exist in catalog.json at all — most likely
      // the catalog hasn't been generated yet, or the folder name in
      // Cloudinary doesn't match categories.ts.
      return {
        products: [],
        loading: false,
        error:
          `No entry for "${category.slug}" in the product catalog. Run "npm run catalog" ` +
          `to (re)generate it from Cloudinary, and make sure the folder name in Cloudinary ` +
          `matches "${category.slug}" exactly.`,
      };
    }

    return { products: toDisplayProducts(resources, category), loading: false, error: null };
  }, [category]);
}

interface AllProductsState {
  products: DisplayProduct[];
  loading: boolean;
  error: string | null;
}

/** All products across every category — used for the site-wide search box. */
export function useAllProducts(enabled: boolean): AllProductsState {
  return useMemo(() => {
    if (!enabled) return { products: [], loading: false, error: null };

    const products = categoryList.flatMap((category) =>
      toDisplayProducts(catalog[category.slug] ?? [], category)
    );

    return { products, loading: false, error: null };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [enabled]);
}

interface CoversState {
  covers: Record<string, string>; // slug -> image url
  loading: boolean;
}

/** First image of every category, used as tile thumbnails on the home page. */
export function useCategoryCovers(): CoversState {
  return useMemo(() => {
    const covers: Record<string, string> = {};
    for (const category of categoryList) {
      const first = catalog[category.slug]?.[0];
      covers[category.slug] = first ? cloudinaryImageUrl(first.public_id, { width: 500, height: 500 }) : '';
    }
    return { covers, loading: false };
  }, []);
}